language: python
python:
    - 2.6
    - 2.7
    - 3.4
notifications:
  slack: ajenti:ANVVc21AEbnRLYAWBZlhzAtW
before_install: pip install coverage
script: nosetests --with-coverage --cover-package=jadi
